### ISSUE TITLE
A question about visualization

### ISSUE THREAD

**Issue by ShiguangSun** [facebookresearch/denoised_mdp#14]
I find that there exists the "floor" in the visualization image when I run a video background experiment. Like this:
![test_episode_0005000](https://user-images.githubusercontent.com/77392434/235107364-7dc43958-967c-4d6b-b31d-44de0520d2f0.png)

And I notice that the video shown in the repository has no floor:
![1](https://user-images.githubusercontent.com/77392434/235110758-94d607ce-fde8-4f26-8336-303f408fa99e.png)

Is the question I meet normal？
Thanks.

**Comment by ssnl** [comment]
Hi @ShiguangSun ! Thanks so much for bringing this to my attention. There is indeed a bug in setting the background removal mode for `walker walk`. It only exists in this public implementation, and now is fixed in https://github.com/facebookresearch/denoised_mdp/commit/1f3b4b38324a762434c7097d3fd2fc84ca4cc909.

Sorry about the bug.

**Comment by ShiguangSun** [comment]
> 

Ok，thanks.
